USE [master]
GO
/****** Object:  Database [PLCS]    Script Date: 8/18/2020 2:57:45 PM ******/
CREATE DATABASE [PLCS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PLCS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PLCS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PLCS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PLCS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PLCS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PLCS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PLCS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PLCS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PLCS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PLCS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PLCS] SET ARITHABORT OFF 
GO
ALTER DATABASE [PLCS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PLCS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PLCS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PLCS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PLCS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PLCS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PLCS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PLCS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PLCS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PLCS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PLCS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PLCS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PLCS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PLCS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PLCS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PLCS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PLCS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PLCS] SET RECOVERY FULL 
GO
ALTER DATABASE [PLCS] SET  MULTI_USER 
GO
ALTER DATABASE [PLCS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PLCS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PLCS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PLCS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PLCS] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'PLCS', N'ON'
GO
ALTER DATABASE [PLCS] SET QUERY_STORE = OFF
GO
USE [PLCS]
GO
/****** Object:  UserDefinedFunction [dbo].[udfNrBorrowedBooks]    Script Date: 8/18/2020 2:57:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[udfNrBorrowedBooks](
    @MemberID INT,
    @MonthName INT
)
RETURNS int
AS 



BEGIN
declare @BookCount int
    set @BookCount = (
	Select	count(BookID) AS BookCount 
	FROM Member_Books 
	WHERE month(Date_Borrowed) = @MonthName
	and CardID = @MemberID)

	RETURN @BookCount
	
END;
GO
/****** Object:  Table [dbo].[Authors]    Script Date: 8/18/2020 2:57:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Authors](
	[AuthorID] [int] NOT NULL,
	[Author_Name] [varchar](50) NULL,
 CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED 
(
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book_Author]    Script Date: 8/18/2020 2:57:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book_Author](
	[BookID] [int] NOT NULL,
	[AuthorID] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Books]    Script Date: 8/18/2020 2:57:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[BookID] [int] NOT NULL,
	[ISBN] [int] NULL,
	[Book_Name] [varchar](50) NULL,
	[NumberOfCopies] [int] NULL,
 CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED 
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Member]    Script Date: 8/18/2020 2:57:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Member](
	[CardID] [int] NOT NULL,
	[Name] [varchar](50) NULL,
	[Address] [varchar](50) NULL,
 CONSTRAINT [PK_Member] PRIMARY KEY CLUSTERED 
(
	[CardID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Member_Books]    Script Date: 8/18/2020 2:57:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Member_Books](
	[CardID] [int] NULL,
	[BookID] [int] NULL,
	[Date_Borrowed] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Book_Author]  WITH CHECK ADD  CONSTRAINT [FK_Book_Author_Authors] FOREIGN KEY([AuthorID])
REFERENCES [dbo].[Authors] ([AuthorID])
GO
ALTER TABLE [dbo].[Book_Author] CHECK CONSTRAINT [FK_Book_Author_Authors]
GO
ALTER TABLE [dbo].[Book_Author]  WITH CHECK ADD  CONSTRAINT [FK_Book_Author_Books] FOREIGN KEY([BookID])
REFERENCES [dbo].[Books] ([BookID])
GO
ALTER TABLE [dbo].[Book_Author] CHECK CONSTRAINT [FK_Book_Author_Books]
GO
ALTER TABLE [dbo].[Member_Books]  WITH CHECK ADD  CONSTRAINT [FK_Member_Books_Books] FOREIGN KEY([BookID])
REFERENCES [dbo].[Books] ([BookID])
GO
ALTER TABLE [dbo].[Member_Books] CHECK CONSTRAINT [FK_Member_Books_Books]
GO
ALTER TABLE [dbo].[Member_Books]  WITH CHECK ADD  CONSTRAINT [FK_Member_Books_Member] FOREIGN KEY([CardID])
REFERENCES [dbo].[Member] ([CardID])
GO
ALTER TABLE [dbo].[Member_Books] CHECK CONSTRAINT [FK_Member_Books_Member]
GO
/****** Object:  StoredProcedure [dbo].[spGetMostBorrowedAuthor]    Script Date: 8/18/2020 2:57:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spGetMostBorrowedAuthor] 
(@Year int)
AS

BEGIN
	SELECT count(a.BookID) AS BookCount,year(a.Date_Borrowed) AS YearBorrowed,b.AuthorID 
		INTO #tmp1
	FROM Member_Books a INNER JOIN Book_Author b
	ON a.BookID=b.BookID
	WHERE year(a.Date_Borrowed) = @Year
	GROUP BY year(a.Date_Borrowed),b.AuthorID


	SELECT top 5 t.AuthorID, a.Author_Name,BookCount 
	FROM #tmp1 t
	INNER JOIN Authors a
	ON t.AuthorID = a.AuthorID
	ORDER BY BookCount DESC

END
GO
USE [master]
GO
ALTER DATABASE [PLCS] SET  READ_WRITE 
GO
